parameters:
    jonasarts.pagination.class: jonasarts\Bundle\PaginationBundle\Services\Pagination

services:
    pagination:
        class: %jonasarts.pagination.class%
        arguments: [ @service_container, @twig ]